# Site settings
title: Theme
email: example@example.org
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# Build settings
markdown: kramdown
